language: bash
sudo: required
dist: trusty
before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
script:
  - env -i TERM=xterm bash -c "bats ./test.bats"
